### ISSUE TITLE
複数のユーザが同じ名前で登録してしまったらどうしよう？

### ISSUE THREAD

**Issue by nanae772** [line-school2018summer/fukuoka-a-client#25]
# 問題点
友だち検索したときに、同じ名前のユーザがいっぱいいたら誰を友だち登録したらよいのか分からなくなってしまう。

# 対策
- ユーザ登録するとき既にそのユーザ名で登録されていたら登録できないようにする
- ユーザ名はかぶってもいいけど、ユーザ検索する用のIDは別で作っておいてそれを一意にするようにして、検索するときはそれを使う

簡単そうなのは前者？東京のどっかのチームは後者を採用していた様子。

**Comment by nemurin** [comment]
サーバー上ではユーザーIDを主キーとして考えてるので、ユーザーID検索がいいと思います。

**Comment by nanae772** [comment]
話し合いにより、ユーザに登録させるときに表示したい名前とは別に一意なIDも登録させる方向でやることにしました。
