### ISSUE TITLE
friendsFragmentからtalkActivityへの画面遷移

### ISSUE THREAD

**Issue by Tokky-tane** [line-school2018summer/fukuoka-a-client#37]
## 必要な引数
- [ ] roomId
- [ ] userId

**Comment by nanae772** [comment]
talkActivityに値を渡すにはputExtra, getExtraメソッドを使えばよさそうですね
RoomItemにはroomIdを持たせてあるので、クリックしたときにそれをもらってuserIdはローカルDBのrooms_usersテーブルから対応するuserIdを選んでくる感じになるでしょうか
